# Netlify configuration file

# This rule applies the X-Robots-Tag header to all pages on your site.
# It tells all crawlers that they are welcome to index your content fully.
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1"
